# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Hola mundo practica clase

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - name : "Hello world"
      run: echo "Hello world"

    - name : Dime la fecha
      run: date
    - name : Muestra el contenido del directorio
      run: dir
    
      